<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>ExpensesControl.Domain</RootNamespace>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Data.Context.Package" Version="1.1.7" />
		<PackageReference Include="CodeFlow.Start.Package" Version="1.1.40" />
	  <PackageReference Include="Destructurama.Attributed" Version="5.1.0" />
	</ItemGroup>
</Project>
